[tool.poetry]
name = "datasette-mailto-links"
version = "0.2.1"
description = "Datasette plugin to render email addresses as mailto: links"
authors = ["chris48s"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/chris48s/datasette-mailto-links"

[tool.poetry.dependencies]
python = "^3.7"
datasette = ">0"

[tool.poetry.dev-dependencies]
isort = "^5.10"
flake8 = "^4.0.1"
black = { version = "==21.11b0", allow-prereleases = true }
pytest = "^6.2.5"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins.datasette]
mailto_links = "datasette_mailto_links"
